-- Run ONCE in the Supabase SQL editor (owner action, same convention as every
-- table here). Until this table exists, the Model Day lane fails closed: no
-- A/B runs can be created, and nothing else changes.
--
-- model_day_runs (printing-press plan, "Model Day" standing ritual): private
-- A/B text runs — the SAME chapter generated by the incumbent model and one
-- challenger, judged blind. A run NEVER touches chapter_workups,
-- chapter_workup_versions, publishing, or the selected models: its only
-- outputs are this row and its cost-ledger events. One row per run attempt;
-- rows are never updated except the status transitions
--   generating -> running (atomic worker consume, BEFORE any spend)
--   generating -> failed  (failed trigger: worker provably never invoked)
--   running    -> done | failed
--   done: verdict/verdict_note/verdict_recorded_at set EXACTLY ONCE
--         (conditional on verdict still null) — the only post-done write
--   (a stale generating/running claim past the worker's maximum lifetime may
--    be conditionally failed by the next create — see model-day.ts)
-- enforced by conditional writes in lib/server/model-day.ts. The partial
-- unique index makes the row insert itself the single-use claim: only one
-- live Model Day run can exist per chapter at a time.
--
-- BLIND SEAL, storage-enforced: label_map ({"A": "<model>", "B": "<model>"})
-- is stored here and EXCLUDED from the judge packet — the judge sees
-- candidates A/B only. The reveal action refuses until a verdict row is
-- durably recorded for the exact packet digest (Codex #103 P2).
create table if not exists model_day_runs (
  id uuid primary key,
  slug text not null,
  status text not null check (status in ('generating','running','done','failed')),
  job_id text not null,
  incumbent_model text not null,
  challenger_model text not null,
  candidate_a_json jsonb,
  candidate_b_json jsonb,
  label_map jsonb,
  packet_digest text,
  verdict text check (verdict in ('A','B','tie')),
  verdict_note text,
  verdict_recorded_at timestamptz,
  schema_version text,
  error text,
  cost_usd numeric,
  created_at timestamptz not null default now()
);

create unique index if not exists model_day_runs_one_live
  on model_day_runs (slug)
  where status in ('generating','running');

create index if not exists model_day_runs_slug_created
  on model_day_runs (slug, created_at desc);

alter table model_day_runs enable row level security;
-- No policies on purpose: service-role access only, like the other tables.
grant select, insert, update on model_day_runs to service_role;
